# Generated by Django 3.1.1 on 2024-03-22 00:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 0, 7, 35, 952493, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
