# Generated by Django 3.1.1 on 2024-03-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyauth', '0005_auto_20240322_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(max_length=1300, null=True),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=models.CharField(max_length=1300, null=True),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='token_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
