# Generated by Django 3.2.11 on 2024-04-11 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotifyauth', '0006_auto_20240322_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_score', models.IntegerField(default=0)),
                ('spotify_linked', models.BooleanField(default=False)),
                ('spotify_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotifyauth.spotifytoken')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
